Add Course, Lesson, StudentLessonResult models, serializers, views
TonikX/online_notebook pull request #4
Opened 2020-05-23 19:28 UTC by kantegory

Добавил модельки, сериализаторы и эндпоинты для Курса, Урока, Результата урока (активность).

По идее, это пункт 2.7.

2020-05-26 15:15 UTC, TonikX requested changes
Комменты в коде.

2020-05-26 15:15 UTC, TonikX commented on application/courses_app/models.py
> +    group_in_stream = models.ForeignKey(GroupInStream, on_delete=models.CASCADE)
Нужно предусмотреть возможность ссылки либо на поток, либо на группу, чтобы можно было проводить урок или для потока групп, или для группы.

2020-05-26 15:15 UTC, TonikX commented on application/courses_app/models.py
> +
Дата?

2020-05-27 20:06 UTC, kantegory commented on application/courses_app/models.py
> +    group_in_stream = models.ForeignKey(GroupInStream, on_delete=models.CASCADE)
Решил делать через опциональные внешние ключи, используя "blank=True, null=True". Другого решения не нашёл.

2020-05-27 20:07 UTC, kantegory commented on application/courses_app/models.py
> +
Перенёс из таблицы lesson_result дату в таблицу lesson

2020-05-30 21:35 UTC, TonikX approved these changes
Принял.

2020-05-30 21:36 UTC, merged